### PR TITLE
Fix EOL removal on Windows.

### LINKED ISSUE #3: Tests fail on Windows
Please add AppVeyor to test things on Windows.

Currently the check for the EOL removal just fails on Windows.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #3.

@brainkim: I added 2 solutions. Which one do you prefer?

### CODE REVIEW

**Comment by XhmikosR** [comment]
@brainkim: I added 2 solutions. Which one do you prefer?

**Comment by XhmikosR** [comment]
Also @brainkim, can you add Travis CI to the repo?

**Comment by XhmikosR** [comment]
On a second thought, do we really need to remove the EOL?

**Comment by XhmikosR** [comment]
@brainkim: please release and publish 0.3.0.

**Comment by brainkim** [comment]
@XhmikosR done :)

**Comment by XhmikosR** [comment]
@brainkim: can you also add Travis to the repo?

**Pull request merged**
